"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useSession } from "next-auth/react";

import { useRequireAuth } from "@/components/auth-guard";
import { SiteShell } from "@/components/site-shell";
import { Card, CardDescription, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { apiFetch } from "@/lib/api";

type EventItem = {
  id: string;
  parcel_id: string;
  address: string;
  event_type: string;
  severity: string;
  details: Record<string, unknown>;
  created_at: string;
};

type EventsResponse = {
  status: string;
  filters: Record<string, unknown>;
  items: EventItem[];
};

export default function OpportunityEventsPage() {
  const { status } = useRequireAuth();
  const { data: session } = useSession();
  const [severity, setSeverity] = useState("");
  const [days, setDays] = useState("30");
  const [events, setEvents] = useState<EventItem[]>([]);

  const query = useMemo(() => {
    const params = new URLSearchParams();
    params.set("days", String(Math.max(1, Number(days) || 30)));
    if (severity.trim()) {
      params.set("severity", severity.trim());
    }
    return params.toString();
  }, [days, severity]);

  useEffect(() => {
    if (!session) return;
    apiFetch<EventsResponse>(`/opportunities/events?${query}`, (session as any).apiToken)
      .then((payload) => setEvents(payload.items || []))
      .catch(() => setEvents([]));
  }, [session, query]);

  if (status !== "authenticated") {
    return null;
  }

  return (
    <SiteShell>
      <Card className="mb-4">
        <CardTitle>Opportunity Events</CardTitle>
        <CardDescription>Threshold-cross and exposure events generated by the opportunities engine.</CardDescription>
        <div className="mt-2">
          <Link className="text-sm text-accent underline" href="/opportunities">
            Back to opportunities
          </Link>
        </div>
        <div className="mt-4 grid gap-2 md:grid-cols-2">
          <Input placeholder="Severity (optional)" value={severity} onChange={(e) => setSeverity(e.target.value)} />
          <Input placeholder="Days" value={days} onChange={(e) => setDays(e.target.value)} />
        </div>
      </Card>

      <div className="space-y-3">
        {events.map((event) => (
          <Card key={event.id} className="p-4">
            <p className="font-semibold">{event.address}</p>
            <p className="text-sm text-muted-foreground">
              {event.event_type.replaceAll("_", " ")} ({event.severity})
            </p>
            <p className="text-xs text-muted-foreground">{new Date(event.created_at).toLocaleString()}</p>
          </Card>
        ))}
        {!events.length ? <Card className="p-4">No events found for the selected filters.</Card> : null}
      </div>
    </SiteShell>
  );
}
